---
on:
  push:
    tags:
      - v*
jobs:
  deploy:
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Create release
        run: make release
