---
name: "Release a tag"
on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GOLANGCI_LINT_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Create release
        run: make release
